services:
    v12mike.postoftheday.functions:
        class: v12mike\postoftheday\core\postoftheday
        arguments:
            - @auth
            - @config
            - @cache
            - @content.visibility
            - @dbal.conn
            - @dispatcher
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%

    v12mike.topfive.listener:
        class: v12mike\postoftheday\event\listener
        arguments:
            - @v12mike.postoftheday.functions
            - @config
            - @template
            - @user
        tags:
            - { name: event.listener }
